### ISSUE TITLE
DAO throws exception on 4xx and 5xx responses

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#1001]
## Describe the bug
Spring's `RestTemplate` by default throws an exception while handling 4xx and 5xx responses, this happens before we are able to handle the response ourselves. So, it effectively bypasses our own error handling.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Make an authentication call with MenasRestDAO using wrong credentials
2. See error

## Expected behaviour
DAO should handle 4xx and 5xx responses with retries when unathorized and throw a custom exception for better clarity.

## Stacktrace
```
org.springframework.web.client.RestClientException: Error running rest call; nested exception is org.springframework.web.client.HttpServerErrorException: 500 
	at org.springframework.security.kerberos.client.KerberosRestTemplate.doExecute(KerberosRestTemplate.java:196)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:262)
	at za.co.absa.enceladus.dao.SpnegoAuthClient.requestAuthentication(AuthClient.scala:90)
	at za.co.absa.enceladus.dao.AuthClient.authenticate(AuthClient.scala:55)
	at za.co.absa.enceladus.dao.RestClient.authenticate(RestClient.scala:33)
	at za.co.absa.enceladus.dao.MenasRestDAO.authenticate(MenasRestDAO.scala:31)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.main(DynamicConformanceJob.scala:63)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob.main(DynamicConformanceJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
Caused by: org.springframework.web.client.HttpServerErrorException: 500 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:614)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:570)
	at org.springframework.security.kerberos.client.KerberosRestTemplate.doExecuteSubject(KerberosRestTemplate.java:202)
	at org.springframework.security.kerberos.client.KerberosRestTemplate.access$100(KerberosRestTemplate.java:67)
	at org.springframework.security.kerberos.client.KerberosRestTemplate$1.run(KerberosRestTemplate.java:191)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:360)
	at org.springframework.security.kerberos.client.KerberosRestTemplate.doExecute(KerberosRestTemplate.java:187)
```

**Comment by GeorgiChochov** [comment]
## For release notes:
Fixed issue with how `Standardization` and `Conformance` handle 4xx and 5xx response from Menas. Error codes due to expired session will now be reauthenticated automatically (as intended) and exceptions will now have a more specific type.
