### ISSUE TITLE
Jenkins builds fail randomly

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1238]
## Describe the bug
```
[2020-03-23T13:25:59.013Z] AuthenticationIntegrationSuite:
[2020-03-23T13:25:59.274Z] Username and password authentication
[2020-03-23T13:25:59.866Z] - should handle multiple users login in concurrently *** FAILED ***
[2020-03-23T13:25:59.866Z]   java.util.concurrent.TimeoutException: Futures timed out after [500 milliseconds]
[2020-03-23T13:25:59.866Z]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:223)
[2020-03-23T13:25:59.866Z]   at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:227)
[2020-03-23T13:25:59.866Z]   at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190)
[2020-03-23T13:25:59.866Z]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[2020-03-23T13:25:59.866Z]   at scala.concurrent.Await$.result(package.scala:190)
[2020-03-23T13:25:59.866Z]   at za.co.absa.enceladus.menas.integration.controllers.AuthenticationIntegrationSuite$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AuthenticationIntegrationSuite.scala:49)
[2020-03-23T13:25:59.866Z]   at za.co.absa.enceladus.menas.integration.controllers.AuthenticationIntegrationSuite$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(AuthenticationIntegrationSuite.scala:42)
[2020-03-23T13:25:59.866Z]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[2020-03-23T13:25:59.866Z]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[2020-03-23T13:25:59.866Z]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[2020-03-23T13:25:59.866Z]   ...
```

## To Reproduce
Run a build on Jenkins.

## Expected behaviour
All tests should pass as they do on a local machine.

**Comment by Zejnilovic** [comment]
This has not happened in newer versions
