### ISSUE TITLE
Menas can return 201 with empty body

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1240]
## Describe the bug
This happens (presumably) when a run creation request is received during a period of very high load. This happens after 30 seconds. from the start of the query

## To Reproduce
* Run 1000 Standardization jobs at once

## Expected behaviour
* The timeout should be configurable
* The backend should return a 5xx response.

## Screenshots
```
20/03/24 06:10:40 ERROR Client: Application diagnostics message: User class threw exception: java.lang.NullPointerException
@at com.shaded.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:871)
@at com.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
@at za.co.absa.enceladus.dao.rest.JsonSerializer$.fromJson(JsonSerializer.scala:39)
@at za.co.absa.enceladus.dao.rest.RestClient.send(RestClient.scala:82)
@at za.co.absa.enceladus.dao.rest.RestClient.sendPost(RestClient.scala:53)
@at za.co.absa.enceladus.dao.rest.MenasRestDAO$$anonfun$storeNewRunObject$1.apply(MenasRestDAO.scala:65)
@at za.co.absa.enceladus.dao.rest.MenasRestDAO$$anonfun$storeNewRunObject$1.apply(MenasRestDAO.scala:63)
@at za.co.absa.enceladus.dao.rest.CrossHostApiCaller$$anonfun$za$co$absa$enceladus$dao$rest$CrossHostApiCaller$$attempt$1$3.apply(CrossHostApiCaller.scala:44)
@at scala.util.Try$.apply(Try.scala:192)
@at za.co.absa.enceladus.dao.rest.CrossHostApiCaller.za$co$absa$enceladus$dao$rest$CrossHostApiCaller$$attempt$1(CrossHostApiCaller.scala:43)
@at za.co.absa.enceladus.dao.rest.CrossHostApiCaller.call(CrossHostApiCaller.scala:57)
@at za.co.absa.enceladus.dao.rest.MenasRestDAO.storeNewRunObject(MenasRestDAO.scala:63)
@at za.co.absa.enceladus.dao.menasplugin.EventListenerMenas.onLoad(EventListenerMenas.scala:66)
@at za.co.absa.atum.core.ControlFrameworkState$$anonfun$initializeProcessor$1.apply(ControlFrameworkState.scala:262)
@at za.co.absa.atum.core.ControlFrameworkState$$anonfun$initializeProcessor$1.apply(ControlFrameworkState.scala:261)
@at scala.collection.immutable.List.foreach(List.scala:392)
@at za.co.absa.atum.core.ControlFrameworkState.initializeProcessor(ControlFrameworkState.scala:261)
@at za.co.absa.atum.core.ControlFrameworkState.addEventListener(ControlFrameworkState.scala:234)
@at za.co.absa.atum.core.Atum$.addEventListener(Atum.scala:223)
@at za.co.absa.atum.plugins.PluginManager$.loadPlugin(PluginManager.scala:22)
@at za.co.absa.enceladus.dao.menasplugin.MenasPlugin$.enableMenas(MenasPlugin.scala:47)
@at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:93)
@at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
@at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
@at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
@at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
@at java.lang.reflect.Method.invoke(Method.java:498)
@at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
```

**Comment by Zejnilovic** [comment]
To simulate put
```scala 
def create(item: C): Future[C] = {
    val a = mongoRepository.create(item).map(_ => item)
    Thread.sleep(90000)
    a
  }
```

in `za/co/absa/enceladus/menas/services/ModelService.scala`

**Comment by yruslan** [comment]
Will do. Thanks!

**Comment by yruslan** [comment]
ToDo
- [ ] Add an index to `run.uniqueId` when a new DB is created or an old one is migrated from the previous version of Menas.
- [ ] Add indexes for other fields that are used for aggregation queries.

**Comment by yruslan** [comment]
Release notes
Hotfix - Added a fix to prevent successful response on request timeouts. Added index for `run.uniqueId` so that updating control measurements do not require a full collection scan.
