### ISSUE TITLE
Dataset deserialization  issue when running HyperConformance

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1252]
## Describe the bug
When HyperConformance runs with Hyperdrive 3.0.0 and a dataset has conformance rules the following exception is thrown:
```
Caused by: com.shaded.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of za.co.absa.enceladus.model.conformanceRule.package$ConformanceRule, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
at [Source: {"name":"Test","version":4,"description":"Test.raw","hdfsPath":"/tmp/Test","hdfsPublishPath":"/tmp/TestPublish","schemaName":"Test","schemaVersion":2,"dateCreated":"2020-04-03T11:55:03.618Z","userCreated":"test","lastUpdated":"2020-04-03T12:09:19.06Z","userUpdated":"test","disabled":false,"dateDisabled":null,"userDisabled":null,"conformance":[{"_t":"MappingConformanceRule","order":0,"controlCheckpoint":true,"mappingTable":"SourceSystemMappingTable","mappingTableVersion":15,"attributeMappings":{"RawFeedName":"testTable"},"targetAttribute":"TestAttribute","outputColumn":"ConformedField","isNullSafe":true},{"_t":"MappingConformanceRule","order":1,"controlCheckpoint":true,"mappingTable":"TestMappingTable","mappingTableVersion":3,"attributeMappings":{"TestSystem":"ConfirmedSystem","RawFeedName":"Name"},"targetAttribute":"TestAttribute","outputColumn":"Conformed","isNullSafe":true},{"_t":"MappingConformanceRule","order":2,"controlCheckpoint":true,"mappingTable":"Test2MappingTable","mappingTableVersion":9,"attributeMappings":{"InputValue":"Name","Test2":"ConfirmedTest2"},"targetAttribute":"Test3","outputColumn":"ConformedTest3","isNullSafe":true}],"parent":{"collection":"dataset","name":"Test","version":3},"schedule":null,"createdMessage":{"menasRef":{"collection":null,"name":"Test","version":4},"updatedBy":"test","updated":"2020-04-03T12:09:19.06Z","changes":[{"field":"","oldValue":null,"newValue":null,"message":"Dataset Test created."}]}}; line: 1, column: 466] (through reference chain: za.co.absa.enceladus.model.Dataset["conformance"]->com.shaded.fasterxml.jackson.module.scala.deser.BuilderWrapper[0])
at com.shaded.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
at com.shaded.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:892)
at com.shaded.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:139)
at com.shaded.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
at com.shaded.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
at com.shaded.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:76)
at com.shaded.fasterxml.jackson.module.scala.deser.SeqDeserializer.deserialize(SeqDeserializerModule.scala:59)
at com.shaded.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:378)
at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1099)
at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:296)
at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
at com.shaded.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
at com.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
at za.co.absa.enceladus.dao.rest.JsonSerializer$.fromJson(JsonSerializer.scala:39)
at za.co.absa.enceladus.dao.rest.RestClient.send(RestClient.scala:82)
at za.co.absa.enceladus.dao.rest.RestClient.sendGet(RestClient.scala:42)
at za.co.absa.enceladus.dao.rest.MenasRestDAO$$anonfun$getDataset$1.apply(MenasRestDAO.scala:36)
at za.co.absa.enceladus.dao.rest.MenasRestDAO$$anonfun$getDataset$1.apply(MenasRestDAO.scala:34)
at za.co.absa.enceladus.dao.rest.CrossHostApiCaller$$anonfun$za$co$absa$enceladus$dao$rest$CrossHostApiCaller$$attempt$1$3.apply(CrossHostApiCaller.scala:44)
at scala.util.Try$.apply(Try.scala:192)
at za.co.absa.enceladus.dao.rest.CrossHostApiCaller.za$co$absa$enceladus$dao$rest$CrossHostApiCaller$$attempt$1(CrossHostApiCaller.scala:43)
at za.co.absa.enceladus.dao.rest.CrossHostApiCaller.call(CrossHostApiCaller.scala:57)
at za.co.absa.enceladus.dao.rest.MenasRestDAO.getDataset(MenasRestDAO.scala:34)
at za.co.absa.enceladus.conformance.HyperConformance.transform(HyperConformance.scala:52)
at za.co.absa.hyperdrive.driver.SparkIngestor$.ingest(SparkIngestor.scala:75)
```

## To Reproduce
Run HyperConformance on dataset that has at least 1 conformance rule.

## Expected behaviour
No exception should be thrown.

**Comment by yruslan** [comment]
Release notes
Fix an issue that lead to a failure to deserialize dataset returned from Menas resulting in a failure of Standardization and streaming conformance.
