### ISSUE TITLE
An exception is thrown at the end of the job

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1277]
## Describe the bug

This exception is thrown at the end of a job if Kafka control metrics plugin is enabled. The job successfully finishes though.

```
20/04/16 09:47:46 INFO ControlInfoProducerKafka: Sending control measurements to dq.control.info...
20/04/16 09:47:46 ERROR ControlInfoProducerKafka: Error sending control info metrics to Kafka.
java.lang.IllegalStateException: Cannot perform operation after producer has been closed
	at org.apache.kafka.clients.producer.KafkaProducer.throwIfProducerClosed(KafkaProducer.java:853)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:862)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:846)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:733)
	at za.co.absa.enceladus.plugins.builtin.common.mq.kafka.ControlInfoProducerKafka.send(ControlInfoProducerKafka.scala:70)
	at za.co.absa.enceladus.plugins.builtin.controlinfo.mq.ControlInfoSenderPlugin.onCheckpoint(ControlInfoSenderPlugin.scala:41)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$za$co$absa$enceladus$common$plugin$menas$EventListenerMenas$$notifyPlugins$1$$anonfun$apply$1.apply(EventListenerMenas.scala:177)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$za$co$absa$enceladus$common$plugin$menas$EventListenerMenas$$notifyPlugins$1$$anonfun$apply$1.apply(EventListenerMenas.scala:175)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$za$co$absa$enceladus$common$plugin$menas$EventListenerMenas$$notifyPlugins$1.apply(EventListenerMenas.scala:175)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$za$co$absa$enceladus$common$plugin$menas$EventListenerMenas$$notifyPlugins$1.apply(EventListenerMenas.scala:174)
	at scala.Option.foreach(Option.scala:257)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas.za$co$absa$enceladus$common$plugin$menas$EventListenerMenas$$notifyPlugins(EventListenerMenas.scala:174)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$onControlMeasurementsUpdated$1.apply(EventListenerMenas.scala:101)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas$$anonfun$onControlMeasurementsUpdated$1.apply(EventListenerMenas.scala:97)
	at scala.Option.foreach(Option.scala:257)
	at za.co.absa.enceladus.common.plugin.menas.EventListenerMenas.onControlMeasurementsUpdated(EventListenerMenas.scala:97)
	at za.co.absa.atum.core.ControlFrameworkState$$anonfun$updateRunCheckpoints$1.apply(ControlFrameworkState.scala:185)
	at za.co.absa.atum.core.ControlFrameworkState$$anonfun$updateRunCheckpoints$1.apply(ControlFrameworkState.scala:184)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at za.co.absa.atum.core.ControlFrameworkState.updateRunCheckpoints(ControlFrameworkState.scala:184)
	at za.co.absa.atum.core.SparkEventListener.onApplicationEnd(SparkEventListener.scala:27)
	at org.apache.spark.scheduler.SparkListenerBus$class.doPostEvent(SparkListenerBus.scala:57)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus$class.postToAll(ListenerBus.scala:91)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$super$postToAll(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply$mcJ$sp(AsyncEventQueue.scala:92)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anonfun$org$apache$spark$scheduler$AsyncEventQueue$$dispatch$1.apply(AsyncEventQueue.scala:87)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:87)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1$$anonfun$run$1.apply$mcV$sp(AsyncEventQueue.scala:83)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1302)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$1.run(AsyncEventQueue.scala:82)
```

## To Reproduce
Run Standardization or Conformance with Kafka control metrics plugin enabled.

## Expected behaviour
No exceptions should be thrown during the normal workflow.

## Additional context
This is blocked by Atum's issue [#25](https://github.com/AbsaOSS/atum/issues/25)

**Comment by yruslan** [comment]
Release notes
Fixed the issue which caused the Kafka control measurement plugin to throw an exception at the end of a Spark job.
