### ISSUE TITLE
Add Spark version check to HyperConformance

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#1293]
## Background
If the version of Spark HyperConformanc is running is less than `2.4.3`, the following exception can be thrown if a conformance rule operates on an array:
```
za.co.absa.hyperdrive.shared.exceptions.IngestionStartException: NOT STARTED ingestion dbcff102-2e4c-49d4-8ad6-14b0165b5f2e. This exception was thrown during the starting of the ingestion job. Check the logs for details.
	at za.co.absa.hyperdrive.driver.SparkIngestor.ingest(SparkIngestor.scala:83)
	at za.co.absa.hyperdrive.driver.IngestionDriver.ingest(IngestionDriver.scala:49)
	at za.co.absa.hyperdrive.driver.drivers.CommandLineIngestionDriver$.main(CommandLineIngestionDriver.scala:38)
	at za.co.absa.hyperdrive.driver.drivers.CommandLineIngestionDriver.main(CommandLineIngestionDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:678)
Caused by: org.apache.spark.sql.catalyst.analysis.UnresolvedException: Invalid call to dataType on unresolved object, tree: lambda 'v1[InnerTestField]
	at org.apache.spark.sql.catalyst.analysis.UnresolvedExtractValue.dataType(unresolved.scala:415)
	at org.apache.spark.sql.catalyst.expressions.Cast.checkInputDataTypes(Cast.scala:210)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$withPlan(Dataset.scala:3407)
	at org.apache.spark.sql.Dataset.select(Dataset.scala:1335)
	at za.co.absa.spark.hats.transformations.NestedArrayTransformations$.nestedWithColumnMapHelper(NestedArrayTransformations.scala:686)
	at za.co.absa.spark.hats.transformations.NestedArrayTransformations$.nestedWithColumnMap(NestedArrayTransformations.scala:55)
	at za.co.absa.spark.hats.Extensions$DataFrameExtension.nestedMapColumn(Extensions.scala:90)
	at za.co.absa.enceladus.conformance.interpreter.rules.CastingRuleInterpreter.conform(CastingRuleInterpreter.scala:51)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:92)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:89)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.applyConformanceRules(DynamicInterpreter.scala:89)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.interpret(DynamicInterpreter.scala:60)
	at za.co.absa.enceladus.conformance.HyperConformance.transform(HyperConformance.scala:54)
	at za.co.absa.hyperdrive.driver.SparkIngestor.ingest(SparkIngestor.scala:79)
	... 8 more
```

## Feature
Add Spark version check to HyperConformance.

**Comment by AdrianOlosutean** [comment]
Release notes:
Add a check to HyperConformance for the Spark version >= 2.3.4
