### ISSUE TITLE
--help throws an error

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#1508]
## Describe the bug
Running `--help` throws an error plus it prints help. Looks very misleading.

## To Reproduce
Steps to reproduce the behavior OR commands run:

```shell
spark-submit --class za.co.absa.enceladus.standardization.StandardizationJob /enceladus/spark-jobs/target/spark-jobs-2.13.0-SNAPSHOT.jar --help
Error: Unknown option --help
Error: Missing option --raw-format
Error: Missing option --dataset-name
Error: Missing option --dataset-version
Error: Missing option --report-date
Error: No authentication method specified (e.g. --menas-auth-keytab)
Job Parameters
Usage: Standardization Job [options]

  -f, --raw-format <value>
                           format of the raw data (csv, xml, parquet, fixed-width, etc.)
  --charset <value>        use the specific charset (default is UTF-8)
  --row-tag <value>        use the specific row tag instead of 'ROW' for XML format
  --delimiter <value>      use the specific delimiter instead of ',' for CSV format
  --csv-quote <value>      use the specific quote character for creating CSV fields that may contain delimiter character(s) (default is '"')
  --csv-escape <value>     use the specific escape character for CSV fields (default is '\')
  --header <value>         use the header option to consider CSV header
  --trimValues <value>     use --trimValues option to trim values in  fixed width file
  --strict-schema-check <value>
                           use --strict-schema-check option to fail or proceed over rows not adhering to the schema (with error in errCol)
  --copybook <value>       Path to a copybook for COBOL data format
  --is-xcom <value>        Does a mainframe file in COBOL format contain XCOM record headers
  --cobol-is-text <value>  Specifies if the mainframe file is ASCII text file
  --cobol-encoding <value>
                           Specify encoding of mainframe files (ascii or ebcdic)
  --cobol-trimming-policy <value>
                           Specify string trimming policy for mainframe files (none, left, right, both)
  --empty-values-as-nulls <value>
                           For FixedWidth file format. Treats empty values as null. Default is false
  --null-value <value>     For FixedWidth file format. Sets the representation of a null value. Defaults is "".
  -D, --dataset-name <value>
                           Dataset name
  -d, --dataset-version <value>
                           Dataset version
  -R, --report-date <value>
                           Report date in 'yyyy-MM-dd' format
  -r, --report-version <value>
                           Report version. If not provided, it is inferred based on the publish path (it's an EXPERIMENTAL feature)
  --menas-auth-keytab <value>
                           Path to keytab file used for authenticating to menas
  --performance-file <value>
                           Produce a performance metrics file at the given location (local filesystem)
  --folder-prefix <value>  Adds a folder prefix before the infoDateColumn
  --persist-storage-level <value>
                           Specifies persistence storage level to use when processing data. Spark's default is MEMORY_AND_DISK.
Exception in thread "main" za.co.absa.enceladus.common.config.ConfigError: Command line parameters error
	at za.co.absa.enceladus.standardization.config.StandardizationConfig$.tryFromArguments(StandardizationConfig.scala:91)
	at za.co.absa.enceladus.standardization.config.StandardizationConfig$.getFromArguments(StandardizationConfig.scala:94)
	at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:32)
	at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2020-08-31 10:26:24,610 INFO util.ShutdownHookManager: Shutdown hook called
2020-08-31 10:26:24,611 INFO util.ShutdownHookManager: Deleting directory /private/var/folders/52/m1m_2cf539gcfvjmr2_9tytr0000gp/T/spark-ded2f06f-3eb0-4afb-ba15-90244f699de7
```

## Expected behaviour
Print only --help when called for it. Do not print issue.

**Comment by AdrianOlosutean** [comment]
Release notes
Running `--help` does not throw misleading errors anymore
