### ISSUE TITLE
HDFS browser doesn't work with EMR HDFS

### ISSUE THREAD

**Issue by lokm01** [AbsaOSS/enceladus#1653]
## Describe the bug
When running menas and pointing it to EMR based HDFS, the service throws the following exception:

`
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [commons-logging.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:985)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResources(WebappClassLoaderBase.java:1086)
	at org.apache.htrace.commons.logging.LogFactory$4.run(LogFactory.java:1388)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.htrace.commons.logging.LogFactory.getResources(LogFactory.java:1407)
	at org.apache.htrace.commons.logging.LogFactory.getConfigurationFile(LogFactory.java:1469)
	at org.apache.htrace.commons.logging.LogFactory.getFactory(LogFactory.java:457)
	at org.apache.htrace.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at org.apache.htrace.Tracer.<clinit>(Tracer.java:33)
	at org.apache.htrace.Trace.isTracing(Trace.java:154)
	at org.apache.htrace.Trace.startSpan(Trace.java:84)
	at org.apache.htrace.Trace.startSpan(Trace.java:70)
	at org.apache.hadoop.hdfs.DFSClient.getPathTraceScope(DFSClient.java:3560)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2115)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1425)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply$mcZ$sp(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
java.lang.ExceptionInInitializerError
	at org.apache.htrace.Trace.isTracing(Trace.java:154)
	at org.apache.htrace.Trace.startSpan(Trace.java:84)
	at org.apache.htrace.Trace.startSpan(Trace.java:70)
	at org.apache.hadoop.hdfs.DFSClient.getPathTraceScope(DFSClient.java:3560)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2115)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1425)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply$mcZ$sp(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [commons-logging.properties]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForResourceLoading(WebappClassLoaderBase.java:1385)
	at org.apache.catalina.loader.WebappClassLoaderBase.findResources(WebappClassLoaderBase.java:985)
	at org.apache.catalina.loader.WebappClassLoaderBase.getResources(WebappClassLoaderBase.java:1086)
	at org.apache.htrace.commons.logging.LogFactory$4.run(LogFactory.java:1388)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.apache.htrace.commons.logging.LogFactory.getResources(LogFactory.java:1407)
	at org.apache.htrace.commons.logging.LogFactory.getConfigurationFile(LogFactory.java:1469)
	at org.apache.htrace.commons.logging.LogFactory.getFactory(LogFactory.java:457)
	at org.apache.htrace.commons.logging.LogFactory.getLog(LogFactory.java:685)
	at org.apache.htrace.Tracer.<clinit>(Tracer.java:33)
	... 20 more
java.lang.NoClassDefFoundError: Could not initialize class org.apache.htrace.Tracer
	at org.apache.htrace.Trace.isTracing(Trace.java:154)
	at org.apache.htrace.Trace.startSpan(Trace.java:84)
	at org.apache.htrace.Trace.startSpan(Trace.java:70)
	at org.apache.hadoop.hdfs.DFSClient.getPathTraceScope(DFSClient.java:3560)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2115)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1305)
	at org.apache.hadoop.hdfs.DistributedFileSystem$22.doCall(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1301)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1425)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply$mcZ$sp(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at za.co.absa.enceladus.menas.services.HDFSService$$anonfun$exists$1.apply(HDFSService.scala:32)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
91057 [http-nio-8080-exec-18] ERROR za.co.absa.enceladus.menas.controllers.RestExceptionHandler - Exception: RestResponse(Request timeout expired.,Some(RequestTimeoutExpiredError(request_timeout_expired)),2021-01-27T11:21:02.990Z[UTC],6f5de5a1-8a7d-480a-966f-92d50bba83d6)
91057 [http-nio-8080-exec-14] ERROR za.co.absa.enceladus.menas.controllers.RestExceptionHandler - Exception: RestResponse(Request timeout expired.,Some(RequestTimeoutExpiredError(request_timeout_expired)),2021-01-27T11:21:02.990Z[UTC],eee13c6d-2ec4-493c-b778-8d1bdd82422c)
org.springframework.web.context.request.async.AsyncRequestTimeoutException
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:390)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:137)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:153)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:238)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
org.springframework.web.context.request.async.AsyncRequestTimeoutException
	at org.springframework.web.context.request.async.TimeoutDeferredResultProcessingInterceptor.handleTimeout(TimeoutDeferredResultProcessingInterceptor.java:42)
	at org.springframework.web.context.request.async.DeferredResultInterceptorChain.triggerAfterTimeout(DeferredResultInterceptorChain.java:79)
	at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$5(WebAsyncManager.java:390)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.onTimeout(StandardServletAsyncWebRequest.java:151)
	at org.apache.catalina.core.AsyncListenerWrapper.fireOnTimeout(AsyncListenerWrapper.java:44)
	at org.apache.catalina.core.AsyncContextImpl.timeout(AsyncContextImpl.java:137)
	at org.apache.catalina.connector.CoyoteAdapter.asyncDispatch(CoyoteAdapter.java:153)
	at org.apache.coyote.AbstractProcessor.dispatch(AbstractProcessor.java:238)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:59)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
`

## To Reproduce
Click add dataset, observe logs.

## Expected behaviour
I should be able to see the list of HDFS folders.

**Comment by benedeki** [comment]
Closing per https://github.com/AbsaOSS/enceladus/pull/1654#issuecomment-770800984
