### ISSUE TITLE
Conformance fails on deserialization of dataset 

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#207]
## Describe the bug
When I try to run conformance job I get an error saying it failed to deserialize dataset

## StackTrace
```bash
2019-03-04 14:01:13 INFO  EnceladusRestDAO:87 - http://localhost:8080/menas/api/dataset/detail/FirstTestData/34
2019-03-04 14:01:13 INFO  EnceladusRestDAO:119 - URL: http://localhost:8080/menas/api/dataset/detail/FirstTestData/34 GET
2019-03-04 14:01:14 INFO  EnceladusRestDAO:89 - {"name":"FirstTestData","version":34,"description":"Next V 31","hdfsPath":"/raw/TestData","hdfsPublishPath":"/alfa/beta/gamaa/delta","schemaName":"FirstTestSchema","schemaVersion":6,"dateCreated":"2019-02-18T14:58:43.787+01:00","userCreated":"user","lastUpdated":"2019-03-04T13:32:00.828+01:00","userUpdated":"user","disabled":false,"dateDisabled":null,"userDisabled":null,"conformance":[{"_t":"LiteralConformanceRule","order":0,"outputColumn":"LiteralColumn","controlCheckpoint":false,"value":"Alfa"}]}
Exception in thread "main" com.shaded.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `za.co.absa.enceladus.model.conformanceRule.package$ConformanceRule` (no Creators, like default construct, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: (String)"{"name":"FirstTestData","version":34,"description":"Next V 31","hdfsPath":"/raw/TestData","hdfsPublishPath":"/alfa/beta/gamaa/delta","schemaName":"FirstTestSchema","schemaVersion":6,"dateCreated":"2019-02-18T14:58:43.787+01:00","userCreated":"user","lastUpdated":"2019-03-04T13:32:00.828+01:00","userUpdated":"user","disabled":false,"dateDisabled":null,"userDisabled":null,"conformance":[{"_t":"LiteralConformanceRule","order":0,"outputColumn":"LiteralColumn","controlCheckpoint":false,"value":"Alfa""[truncated 3 chars]; line: 1, column: 389] (through reference chain: za.co.absa.enceladus.model.Dataset["conformance"]->com.shaded.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$BuilderWrapper[0])
	at com.shaded.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.shaded.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1452)
	at com.shaded.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1028)
	at com.shaded.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:265)
	at com.shaded.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.shaded.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.shaded.fasterxml.jackson.module.scala.deser.GenericFactoryDeserializerResolver$Deserializer.deserialize(GenericFactoryDeserializerResolver.scala:80)
	at com.shaded.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:530)
	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:528)
	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:417)
	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.shaded.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.shaded.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
	at za.co.absa.enceladus.dao.EnceladusRestDAO$.getDataset(EnceladusRestDAO.scala:90)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.main(DynamicConformanceJob.scala:119)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob.main(DynamicConformanceJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2019-03-04 14:01:14 INFO  SparkContext:54 - Invoking stop() from shutdown hook
2019-03-04 14:01:14 INFO  AbstractConnector:318 - Stopped Spark@7d2a6eac{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
2019-03-04 14:01:14 INFO  SparkUI:54 - Stopped Spark web UI at http://192.168.0.186:4041
```

## Command Run
```bash
spark-submit \                                                                                                                                                                                          1 ↵
--num-executors 4 \
--executor-memory 4g \
--master local \
--driver-cores 4 \
--driver-memory 4G \
--conf "spark.driver.extraJavaOptions=-Dmenas.rest.uri=http://localhost:8080/menas/api -Dstandardized.hdfs.path=/publish/testData2-{0}-{1}-{2}-{3} -Dconformance.mappingtable.pattern=reportDate={0}-{1}-{2} -Dspline.mongodb.name='spline_jedi' " \
--class za.co.absa.enceladus.conformance.DynamicConformanceJob \
/Users/absz189/Development/enceladus/conformance/target/enceladus-conformance-0.99.0-SNAPSHOT.jar \
--dataset-name FirstTestData --dataset-version 34 --report-date 2019-02-25 --report-version 1 --menas-credentials-file ~/.ssh/menas-credential.properties
```

## Additional context
- Standardization job on the same passes.
- Built this morning 04/03 2019

**Comment by GeorgiChochov** [comment]
The issue stem from the fact that the `enceladus-dataModel` dependency in the conformance job should be transitive from the `enceladus-dao` dependency. `enceladus-dao` shades the jackson library in order to comply with Spring's jackson version without conflicting with Spark's jackson version. When the `enceladus-dataModel` dependency is explicitly present, the jackson annotations  on the models are unshaded and the shaded `enceldaus-dao` jackson does not recognize them, hence fails to deserialize.
