### ISSUE TITLE
A NullPointerException is thrown at the end of Standardization job

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#223]
## Describe the bug

```
19/03/07 10:18:27 INFO scheduler.DAGScheduler: Job 6 finished: take at StandardizationJob.scala:84, took 0.669104 s
Exception in thread "main" java.lang.NullPointerException
	at za.co.absa.enceladus.standardization.StandardizationJob$.addPerformanceMetadata(StandardizationJob.scala:84)
	at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:210)
	at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
```

This might be an issue in Conformance as well. When this is fixed in Standardization the fix should align Conformance performance metrics gathering routine.

## To Reproduce
1. Run a Standardization job on cluster

## Expected behaviour
The exception is thrown at the moment when the job is gathering performance metadata. This part of the code should be very well protected against exceptions. Even if a job fails to gather performance metrics it should better warn the user, but never throw.

## Desktop (please complete the following information):
 - Linux lab cluster

**Comment by yruslan** [comment]
The reason of the failure is Standardization producing an empty result because a wrong rowtag was specified for a xml input. Still, need to handle this case properly.

Decided to refactor this thing...
