### ISSUE TITLE
Conformance Cast Rule to Char throws unhandled exception

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#425]
## Describe the bug
After creating a casting rule with casting to char I get an error when running conformance. One of the important lines is `DataType char is not supported`.

## To Reproduce
1. Have a Casting rule to char
2. Run conformance
3. See the non zero exit with an error message

## StackTrace
```bash
19/05/28 08:43:10 INFO ControlFrameworkREST: HttpResponseProxy{HTTP/1.1 200  [X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: 0, X-Frame-Options: DENY, X-Content-Type-Options: nosniff, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Tue, 28 May 2019 06:43:10 GMT] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}
19/05/28 08:43:11 INFO ControlFrameworkREST: URL: http://localhost:8080/menas/api/runs/updateRunStatus/255ce26a-e108-4b83-b820-55ce29b504e3 POST: {"status":{"enumClass":"za.co.absa.atum.model.RunState","value":"failed"},"error":{"job":"Dynamic Conformance plasteline 7 2019-02-25 1","step":"Conformance","description":"\nDataType char is not supported.(line 1, pos 0)\n\n== SQL ==\nchar\n^^^\n","technicalDetails":"org.apache.spark.sql.catalyst.parser.ParseException: \nDataType char is not supported.(line 1, pos 0)\n\n== SQL ==\nchar\n^^^\n\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitPrimitiveDataType$1.apply(AstBuilder.scala:1772)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitPrimitiveDataType$1.apply(AstBuilder.scala:1750)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:1750)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:49)\n\tat org.apache.spark.sql.catalyst.parser.SqlBaseParser$PrimitiveDataTypeContext.accept(SqlBaseParser.java:14452)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.typedVisit(AstBuilder.scala:55)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.org$apache$spark$sql$catalyst$parser$AstBuilder$$visitSparkDataType(AstBuilder.scala:1744)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleDataType$1.apply(AstBuilder.scala:90)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleDataType$1.apply(AstBuilder.scala:90)\n\tat org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)\n\tat org.apache.spark.sql.catalyst.parser.AstBuilder.visitSingleDataType(AstBuilder.scala:89)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parseDataType$1.apply(ParseDriver.scala:40)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parseDataType$1.apply(ParseDriver.scala:39)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:100)\n\tat org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseDataType(ParseDriver.scala:39)\n\tat za.co.absa.enceladus.conformance.interpreter.rules.CastingRuleInterpreter.conform(CastingRuleInterpreter.scala:39)\n\tat za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:90)\n\tat za.co.absa.enceladus.conforma"}}
19/05/28 08:43:11 INFO ControlFrameworkREST: HttpResponseProxy{HTTP/1.1 200  [X-Content-Type-Options: nosniff, X-XSS-Protection: 1; mode=block, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: 0, X-Frame-Options: DENY, X-Content-Type-Options: nosniff, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Tue, 28 May 2019 06:43:10 GMT] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Chunked: true]}}
Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException:
DataType char is not supported.(line 1, pos 0)

== SQL ==
char
^^^

	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitPrimitiveDataType$1.apply(AstBuilder.scala:1772)
	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitPrimitiveDataType$1.apply(AstBuilder.scala:1750)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:1750)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitPrimitiveDataType(AstBuilder.scala:49)
	at org.apache.spark.sql.catalyst.parser.SqlBaseParser$PrimitiveDataTypeContext.accept(SqlBaseParser.java:14452)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.typedVisit(AstBuilder.scala:55)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.org$apache$spark$sql$catalyst$parser$AstBuilder$$visitSparkDataType(AstBuilder.scala:1744)
	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleDataType$1.apply(AstBuilder.scala:90)
	at org.apache.spark.sql.catalyst.parser.AstBuilder$$anonfun$visitSingleDataType$1.apply(AstBuilder.scala:90)
	at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:108)
	at org.apache.spark.sql.catalyst.parser.AstBuilder.visitSingleDataType(AstBuilder.scala:89)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parseDataType$1.apply(ParseDriver.scala:40)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser$$anonfun$parseDataType$1.apply(ParseDriver.scala:39)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:100)
	at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseDataType(ParseDriver.scala:39)
	at za.co.absa.enceladus.conformance.interpreter.rules.CastingRuleInterpreter.conform(CastingRuleInterpreter.scala:39)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:90)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:81)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.applyConformanceRules(DynamicInterpreter.scala:81)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.interpret(DynamicInterpreter.scala:61)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.main(DynamicConformanceJob.scala:85)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob.main(DynamicConformanceJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/05/28 08:43:11 INFO spark.SparkContext: Invoking stop() from shutdown hook
19/05/28 08:43:11 INFO server.AbstractConnector: Stopped Spark@5eefa415{HTTP/1.1,[http/1.1]}{0.0.0.0:4041}
19/05/28 08:43:11 INFO ui.SparkUI: Stopped Spark web UI at http://192.168.0.78:4041
19/05/28 08:43:11 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/05/28 08:43:11 INFO memory.MemoryStore: MemoryStore cleared
19/05/28 08:43:11 INFO storage.BlockManager: BlockManager stopped
19/05/28 08:43:11 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
19/05/28 08:43:11 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/05/28 08:43:11 INFO spark.SparkContext: Successfully stopped SparkContext
19/05/28 08:43:11 INFO util.ShutdownHookManager: Shutdown hook called
19/05/28 08:43:11 INFO util.ShutdownHookManager: Deleting directory /private/var/folders/b_/7z9rhc9x5hs5cw9qqdpzyr1m0000gq/T/spark-66dc8422-f43f-415a-ac7f-30a55b3a1622
19/05/28 08:43:11 INFO util.ShutdownHookManager: Deleting directory /private/var/folders/b_/7z9rhc9x5hs5cw9qqdpzyr1m0000gq/T/spark-9ccc1120-e286-4da8-b3e1-19935cc0cc13
```

**Comment by lokm01** [comment]
**https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.types.CharType**

Char is a Hive compatibility type. It's not a full spark SQL type. It shouldn't be supported. This is not a bug.

**Comment by Zejnilovic** [comment]
> **https://spark.apache.org/docs/latest/api/scala/index.html#org.apache.spark.sql.types.CharType**
> 
> Char is a Hive compatibility type. It's not a full spark SQL type. It shouldn't be supported. This is not a bug.

Fair enough. Then we just remove line 167 in `menas/ui/components/dataset/conformanceRule/ConformanceRuleForm.js`
