### ISSUE TITLE
[ERROR] Failed to execute goal on project enceladus-conformance: Could not resolve dependencies for project za.co.absa:enceladus-conformance:jar:0.99.0-SNAPSHOT: The following artifacts could not be resolved: za.co.absa:enceladus-utils:jar:0.99.0-SNAPSHOT, za.co.absa:enceladus-dao:jar:0.99.0-SNAPSHOT: Could not find artifact za.co.absa:enceladus-utils:jar:0.99.0-SNAPSHOT in mongo-absa (https://dl.bintray.com/absa/mongo-absa) -> [Help 1]

### ISSUE THREAD

**Issue by Praveen456B** [AbsaOSS/enceladus#524]

**Comment by lokm01** [comment]
I have a feeling you need to build the top level maven project, not its submodules.

**Comment by lokm01** [comment]
P.S it'd be great if you could fill in the issue template describing your problem properly with as much details as possible when submitting any additional issues.

**Comment by Praveen456B** [comment]
I can able to download all the jars, but this is the only error im facing right now...whats the solution for this?

**Comment by lokm01** [comment]
> I can able to download all the jars, but this is the only error im facing right now...whats the solution for this?

The solution is building the top level project, which will in turn build all of its submodules automatically satisfying these dependencies.

It seems that you're building them one by one.

**Comment by Praveen456B** [comment]
Yes I build the top level project and its working now..Thanks

**Comment by Praveen456B** [comment]
which is the top level project to build ? is that Conformance?

Im getting the below error again and again when i try to build 
**[WARNING] The POM for za.co.absa:enceladus-dao:jar:0.99.0-SNAPSHOT is missing, no dependency information available**

**Comment by Zejnilovic** [comment]
The root of the project has a `pom.xml` file, that is the parent pom (top level) and the artifactId is `enceladus-parent`. Everything found in `modules` tag is a sub-module.

For more questions about how Maven and multimodule projects works please refer to the official [documentation](https://maven.apache.org/pom.html) or look through [StackOverflow](https://stackoverflow.com/questions/tagged/maven) which offers an overwhelming number of question and answers to the maven problematic.

**Comment by Praveen456B** [comment]
Thats working fine now........I put my input file into menas conf file that is in the format of text file.  and when I deploy the code using tomcat server I got the below issues.

what may be the issue?? I have change the hostname everything in menas mongo conf file.

com.mongodb.MongoSocketReadException: Prematurely reached end of stream
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:249)
	at com.mongodb.internal.connection.AsynchronousSocketChannelStream$BasicCompletionHandler.completed(AsynchronousSocketChannelStream.java:235)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
	at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:281)
	at sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:579)
	at sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:397)
	at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[INFO]	2019-06-24 13:54:41,874 [RMI TCP Connection(3)-127.0.0.1] org.apache.spark.SparkContext - Running Spark version 2.4.3
[ERROR]	2019-06-24 13:54:42,912 [RMI TCP Connection(3)-127.0.0.1] org.apache.hadoop.util.Shell - Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
	at org.apache.hadoop.util.Shell.getQualifiedBinPath(Shell.java:382)
	at org.apache.hadoop.util.Shell.getWinUtilsPath(Shell.java:397)
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:390)
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:80)
	at org.apache.hadoop.security.SecurityUtil.getAuthenticationMethod(SecurityUtil.java:610)
	at org.apache.hadoop.security.UserGroupInformation.initialize(UserGroupInformation.java:277)
	at org.apache.hadoop.security.UserGroupInformation.ensureInitialized(UserGroupInformation.java:265)
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:810)
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:780)
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:653)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2422)
	at org.apache.spark.util.Utils$$anonfun$getCurrentUserName$1.apply(Utils.scala:2422)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.util.Utils$.getCurrentUserName(Utils.scala:2422)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:293)
	at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2520)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:935)
	at org.apache.spark.sql.SparkSession$Builder$$anonfun$7.apply(SparkSession.scala:926)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.SparkSession$Builder.getOrCreate(SparkSession.scala:926)
	at za.co.absa.enceladus.menas.SparkConfig.spark(SparkConfig.scala:36)
	at za.co.absa.enceladus.menas.SparkConfig$$EnhancerBySpringCGLIB$$31f654c7.CGLIB$spark$1(<generated>)
	at za.co.absa.enceladus.menas.SparkConfig$$EnhancerBySpringCGLIB$$31f654c7$$FastClassBySpringCGLIB$$dd6c8091.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
	at za.co.absa.enceladus.menas.SparkConfig$$EnhancerBySpringCGLIB$$31f654c7.spark(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:815)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:721)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:192)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)

**Comment by Zejnilovic** [comment]
There is an error message saying you don't have necessary dependencies solved on your machine. Please check your path and winutils installation.

The line referred below:
```
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.
```

**Comment by Praveen456B** [comment]
Yes I neet to setup winutils.exe.....due to this only I cant able to make a connection to mongodb, com.mongodb.MongoSocketReadException: Prematurely reached end of stream??
