### ISSUE TITLE
Can't able to make connections to MongoDB

### ISSUE THREAD

**Issue by Praveen456B** [AbsaOSS/enceladus#538]
## Describe the bug

com.mongodb.MongoSocketOpenException: Exception opening socket
at com.mongodb.internal.connection.AsynchronousSocketChannelStream$OpenCompletionHandler.failed(AsynchronousSocketChannelStream.java:296)
at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:128)
at sun.nio.ch.Invoker$2.run(Invoker.java:218)
at sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused
at sun.nio.ch.UnixAsynchronousSocketChannelImpl.checkConnect(Native Method)
at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishConnect(UnixAsynchronousSocketChannelImpl.java:252)
at sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:198)
at sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:213)
at sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:293)
... 1 more

**Comment by lokm01** [comment]
This suggests that Menas can't connect to mongo - specifically there seems to be nothing running on the port, or its getting rejected by firewall.
Caused by: java.net.ConnectException: Connection refused

**Comment by lokm01** [comment]
This is not an issue on our side!

**Comment by Praveen456B** [comment]
Its working

**Comment by gswain3316** [comment]
How did it work ? I am facing similar issue

**Comment by Zejnilovic** [comment]
> How did it work ? I am facing similar issue

Hello @gswain3316, AFAIK there was just a problem of reaching Mongo from Menas. So an "infrastructure" setup.

So some questions to answer are:
- what do you have in `menas.mongo.connection.string` property?
- is mongo running on that IP and port?
- can you connect to that mongo from terminal or robot 3t?
- can the VM/machine/container running Menas reach the Mongo server?
