### ISSUE TITLE
selenium

### ISSUE THREAD

**Issue by Praveen456B** [AbsaOSS/enceladus#548]
## To Reproduce
Steps to reproduce the behavior OR commands run:
3. Enter value '...'

**Comment by Praveen456B** [comment]
Can you please look into the below issues, I have setup the HADOOP_CONF_DIR correctly but still im getting the below error

Cause: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'HDFSConfig' defined in file [/home/cloudera/Downloads/enceladus-develop/menas/target/classes/za/co/absa/enceladus/menas/HDFSConfig.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [za.co.absa.enceladus.menas.HDFSConfig$$EnhancerBySpringCGLIB$$a6993a14]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Missing HADOOP_CONF_DIR environment variable.
  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:278)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
  ...
  Cause: org.springframework.beans.BeanInstantiationException: Failed to instantiate [za.co.absa.enceladus.menas.HDFSConfig$$EnhancerBySpringCGLIB$$a6993a14]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Missing HADOOP_CONF_DIR environment variable.
  at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:182)
  at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
  at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1270)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1127)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
  ...
  Cause: java.lang.IllegalStateException: Missing HADOOP_CONF_DIR environment variable.
  at za.co.absa.enceladus.menas.HDFSConfig$$anonfun$1.apply(HDFSConfig.scala:48)
  at za.co.absa.enceladus.menas.HDFSConfig$$anonfun$1.apply(HDFSConfig.scala:48)
  at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
  at scala.collection.AbstractMap.getOrElse(Map.scala:59)
  at za.co.absa.enceladus.menas.HDFSConfig.<init>(HDFSConfig.scala:47)
  at za.co.absa.enceladus.menas.HDFSConfig$$EnhancerBySpringCGLIB$$a6993a14.<init>(<generated>)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAcc

**Comment by Zejnilovic** [comment]
Hello Praveen456B,

first of all, selenium is currently not going to work for you. This is a module for testing purposes that provides no functionality, but because of heavy refactoring of the UI we decided to postpone its updates. 

Second of all, this is Xth issue that you have filed within our project and as much as we are happy that someone is taking interest in what we do, we need to ask you to do it more seriously. You write a header with no body, we then cannot even imagine what the issue is, or have to do real detective work. Next time I would ask you to fill the issue contents as well. At least the `To Reproduce` prat. 

Here are some free online articles describing how an issue/bug should be written:
- [Test the Web Forward - How to Report a Bug](http://testthewebforward.org/docs/bugs.html)
- [Sifter - Tips for effectively reporting bugs and issues](https://sifterapp.com/blog/2012/08/tips-for-effectively-reporting-bugs-and-issues/)
- [musescore - How to write a good bug report: step-by-step instructions
](https://musescore.org/en/handbook/developers-handbook/getting-started/how-write-good-bug-report-step-step-instructions)

**Comment by Zejnilovic** [comment]
The stack trace says 
```
Cause: java.lang.IllegalStateException: Missing HADOOP_CONF_DIR environment variable.
```
This issue is not on our side. Setup your Hadoop Env variables first.

**Comment by Praveen456B** [comment]
Hi Team

I know Java so I will look into this issue. And going forward I will
documents the issue correctly, I can't able to do sometimes because I'm in
between my work .

there is any connections between selenium and hdfsConfig? Because it's keep
saying springframework beanInstatiationException:Failed to instantiate
HdfsConfig..

I believe I setup my HADOOP-CONF_DIR correctly but I don't know it's keep
saying missing directory.

Is menas connecting HDFS ? As per the issue number #485 it's not working
sometime? Is that issue resolved??

Regards
Praveen

**Comment by Zejnilovic** [comment]
1. Menas does connect to HDFS and the issue #485 is closed, therefore resolved. You can also see that the stack traces are nowhere near similar.
2. Your `HADOOP-CONF_DIR` has a `-` instead of `_`. It should be `HADOOP_CONF_DIR`
3. Selenium module is only being built and should not cause any issues if you don't run its profile. Don't bother with it.

**Comment by Praveen456B** [comment]
Okay Thanks

**Comment by GeorgiChochov** [comment]
I suppose we can consider this resolved then.
