### ISSUE TITLE
If mapping table folder is empty error message is misleading (talking about schema)

### ISSUE THREAD

**Issue by Zejnilovic** [AbsaOSS/enceladus#748]
## Describe the bug
If a folder in which there is supposed to be a parquet file with mapping table is empty, conformance throws an error about unspecified schema and it needs to be added manually. This can be a big point of confusion.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Point -Dconformance.mappingtable.pattern to an empty folder
2. Run Conformance

## Expected behaviour
I would expect a better error message like mapping table parquet not found or something like that.

## Screenshots
**Runs view**
![image](https://user-images.githubusercontent.com/17467768/62208742-07df8200-b398-11e9-81ac-9c2d74b7de9a.png)

## StackTrace
```bash
Exception in thread "main" org.apache.spark.sql.AnalysisException: Unable to infer schema for Parquet. It must be specified manually.;
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$7.apply(DataSource.scala:185)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:184)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:373)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:223)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:641)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:625)
	at za.co.absa.enceladus.conformance.datasource.DataSource$.getData(DataSource.scala:50)
	at za.co.absa.enceladus.conformance.datasource.DataSource$.getData(DataSource.scala:58)
	at za.co.absa.enceladus.conformance.interpreter.rules.MappingRuleInterpreter.conform(MappingRuleInterpreter.scala:58)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.za$co$absa$enceladus$conformance$interpreter$DynamicInterpreter$$applyConformanceRule(DynamicInterpreter.scala:155)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:95)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$$anonfun$1.apply(DynamicInterpreter.scala:93)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:124)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.applyConformanceRules(DynamicInterpreter.scala:93)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.interpret(DynamicInterpreter.scala:64)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.conform(DynamicConformanceJob.scala:176)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.main(DynamicConformanceJob.scala:88)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob.main(DynamicConformanceJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

## Bonus Points
Also, check if the file is parquet at all. That stack trace is really long, but in that case, someone with patience can read from it that the file was not parquet.

**Comment by yruslan** [comment]
For release notes: fixed error message shown in case a mapping table directory is empty.
