### ISSUE TITLE
Improve LDAP/Kerberos authentication error messages

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#779]
## Background
When a user authenticates via a keytab file and login was not successful, Standardization/Conformance jobs throw NullPointerException.

```
19/08/06 14:51:52 INFO EnceladusRestDAO$: Calling REST with SPNEGO auth some-user@SOME.DOMAIN.COM /home/some-user/keytab.keytab
Exception in thread "main" java.lang.NullPointerException
	at scala.collection.convert.Wrappers$JListWrapper.iterator(Wrappers.scala:88)
	at scala.collection.IterableLike$class.head(IterableLike.scala:107)
	at scala.collection.AbstractIterable.head(Iterable.scala:54)
	at za.co.absa.enceladus.dao.EnceladusRestDAO$.restTemplateLogin(EnceladusRestDAO.scala:98)
	at za.co.absa.enceladus.dao.EnceladusRestDAO$.spnegoLogin(EnceladusRestDAO.scala:121)
	at za.co.absa.enceladus.dao.EnceladusRestDAO$.enceladusLogin(EnceladusRestDAO.scala:78)
	at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:58)
	at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/08/06 14:51:53 INFO SparkContext: Invoking stop() from shutdown hook

```

Similar happens for many authentication issues. The last one encountered has the following related Menas stack trace:

```
org.springframework.security.core.userdetails.UsernameNotFoundException: User some-user not found in directory.
	at org.springframework.security.ldap.search.FilterBasedLdapUserSearch.searchForUser(FilterBasedLdapUserSearch.java:134)
	at za.co.absa.enceladus.menas.auth.kerberos.KerberosLdapUserSearch.searchForUser(KerberosLdapUserSearch.scala:31)
	at org.springframework.security.ldap.userdetails.LdapUserDetailsService.loadUserByUsername(LdapUserDetailsService.java:56)
ERROR za.co.absa.enceladus.menas.auth.kerberos.MenasKerberosAuthentication$ - [Ljava.lang.StackTraceElement;@18965c46
```

## Feature
* Menas should provide basic information about why authentication has failed to the REST caller
* Standardization/Conformance jobs should throw an authentication-related exception and error message instead of throwing NullPointerException.

**Comment by yruslan** [comment]
## For release notes
Improved HTTP status codes and authentication error messages in Standardization in Conformance.
