### ISSUE TITLE
HDFS Browser causes OutOfMemoryException

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#866]
## Describe the bug
The HDFS Browser in Menas queries HDFS for information about the currently open path and its children. To distinguish between the child directories and child files it performs `ls` on each child path. When the child path is a very large directory (e.g., with 250,000 files) it loads all of them into memory and the heap explodes with several million `String`s and `char[]`s causing an `OutOfMemoryException`.
This `ls` is unnecessary as the only information we need from it is to know if the child is a directory or a file.

## Stacktrace
```
ava.lang.OutOfMemoryError: GC overhead limit exceeded
02-Sep-2019 15:15:25.338 INFO [http-nio-8080-exec-8] org.apache.catalina.connector.CoyoteAdapter.checkRecycled Encountered a non-recycled request and recycled it forcedly.
	org.apache.catalina.connector.CoyoteAdapter$RecycleRequiredException
		at org.apache.catalina.connector.CoyoteAdapter.checkRecycled(CoyoteAdapter.java:525)
		at org.apache.coyote.http11.Http11Processor.recycle(Http11Processor.java:1329)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.release(AbstractProtocol.java:1055)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:1023)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:748)
```

## Expected behaviour
Browsing HDFS via Menas should not blow up.
Further improvements to decreasing the load induced by querying HDFS can be gained by #490 and #403.

## Additional context
We found this in one of our environments where loading the `/` path's subdirectories `/spark2-history` blew up.

**Comment by GeorgiChochov** [comment]
The HDFS Browser performs smaller queries, which improves response times and prevents crashes on over-crowded HDFS dirs.
