### ISSUE TITLE
Check if Conformance can be run on a streaming dataframe.

### ISSUE THREAD

**Issue by yruslan** [AbsaOSS/enceladus#897]
## Background
Conforming streaming data is something we would like to have in the future. Although Spark API is similar for batch and stream processing, they are not the same. There is a number of issues we expect to encounter when trying to run Conformance on streaming data.

## Feature
Here is the list of potential transformations that might not work on streams:
1. Error column generation routines from the arrays transformation package. 
2. Mapping rule array explosion/collapse.
3. Control metrics generation (and everything related to INFO-files in general).

The purpose of this task is to log as many issues as possible that occur when trying to conform a streaming dataframe to evaluate the effort required to support such a workflow. The results of this analysis could be used for integrating Conformance as a component of [Hyperdrive](https://github.com/AbsaOSS/hyperdrive).

## Proposed Solution [Optional]
To check and confirm possible issues we can use a Parquet folder as a streaming source. Just replace `.read(...)` with `readStream(...)` (Thanks @felipemmelo!).

**Comment by yruslan** [comment]
The first issue is indeed related to Atum:
```
Exception in thread "main" java.lang.IllegalStateException: Control framework was unable to infer dataset input file name.
	at za.co.absa.atum.utils.ExecutionPlanUtils$.inferInputInfoFileName(ExecutionPlanUtils.scala:48)
	at za.co.absa.atum.core.ControlFrameworkState.initializeControlInfo(ControlFrameworkState.scala:207)
	at za.co.absa.atum.core.ControlFrameworkState.calculateCheckpoint(ControlFrameworkState.scala:103)
	at za.co.absa.atum.AtumImplicits$DataSetWrapper.setCheckpoint(AtumImplicits.scala:226)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.applyCheckpoint(DynamicInterpreter.scala:191)
	at za.co.absa.enceladus.conformance.interpreter.DynamicInterpreter$.interpret(DynamicInterpreter.scala:53)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.conform(DynamicConformanceJob.scala:191)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.main(DynamicConformanceJob.scala:90)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob.main(DynamicConformanceJob.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:849)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:167)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:195)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:924)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:933)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Going to turn off Control Measurements for now and retry.

**Comment by yruslan** [comment]
The item 2 is confirmed as well:
```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Append output mode not supported when there are streaming aggregations on streaming DataFrames/DataSets without watermark;;
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.org$apache$spark$sql$catalyst$analysis$UnsupportedOperationChecker$$throwError(UnsupportedOperationChecker.scala:389)
	at org.apache.spark.sql.catalyst.analysis.UnsupportedOperationChecker$.checkForStreaming(UnsupportedOperationChecker.scala:111)
	at org.apache.spark.sql.streaming.StreamingQueryManager.createQuery(StreamingQueryManager.scala:250)
	at org.apache.spark.sql.streaming.StreamingQueryManager.startQuery(StreamingQueryManager.scala:316)
	at org.apache.spark.sql.streaming.DataStreamWriter.start(DataStreamWriter.scala:325)
	at za.co.absa.enceladus.conformance.DynamicConformanceJob$.processResult(DynamicConformanceJob.scala:235)
```
Need to rethink how to implement mapping rule streaming friendly.

**Comment by yruslan** [comment]
Conformance with a casting rule on a dataset that does not have an array works on streaming. 

Now the last thing left to check is a casting rule on a field inside an array. If it works, the streaming support is blocked only by the mapping rule.

**Comment by yruslan** [comment]
Item 1 is not an issue. All conformance rules work, except the mapping one.
So in order to support Enceladus on streaming we need:
1. Implement a stream-friendly mapping rule.
2. Think about what approach to use for control measurements (this can be decided much later).
