### ISSUE TITLE
Standardization fails to serialize special characters when updating Run in Menas

### ISSUE THREAD

**Issue by GeorgiChochov** [AbsaOSS/enceladus#989]
## Describe the bug
When running Standardization on a csv file, with a special character delimeter the job fails when trying to update the Run's ControlMeasure.

## To Reproduce
Steps to reproduce the behavior OR commands run:
1. Run Standardization on a csv file with a delimeter `¡`
2. See exception

## Expected behaviour
Standardization should succeed.

## Standardization Stacktrace
```
Unable to update control measurements for a Run object (bef92251-66b6-4b54-a158-b58f36fc9508) in the database
        at za.co.absa.enceladus.dao.menasplugin.EventListenerMenas$$anonfun$onControlMeasurementsUpdated$1.apply(EventListenerMenas.scala:85)
        at za.co.absa.enceladus.dao.menasplugin.EventListenerMenas$$anonfun$onControlMeasurementsUpdated$1.apply(EventListenerMenas.scala:81)
        at scala.Option.foreach(Option.scala:257)
        at za.co.absa.enceladus.dao.menasplugin.EventListenerMenas.onControlMeasurementsUpdated(EventListenerMenas.scala:81)
        at za.co.absa.atum.core.ControlFrameworkState$$anonfun$updateRunCheckpoints$1.apply(ControlFrameworkState.scala:185)
        at za.co.absa.atum.core.ControlFrameworkState$$anonfun$updateRunCheckpoints$1.apply(ControlFrameworkState.scala:184)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at za.co.absa.atum.core.ControlFrameworkState.updateRunCheckpoints(ControlFrameworkState.scala:184)
        at za.co.absa.atum.core.ControlFrameworkState.calculateCheckpoint(ControlFrameworkState.scala:122)
        at za.co.absa.atum.AtumImplicits$DataSetWrapper.setCheckpoint(AtumImplicits.scala:225)
        at za.co.absa.enceladus.standardization.StandardizationJob$.executeStandardization(StandardizationJob.scala:310)
        at za.co.absa.enceladus.standardization.StandardizationJob$.main(StandardizationJob.scala:106)
        at za.co.absa.enceladus.standardization.StandardizationJob.main(StandardizationJob.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
Caused by: org.springframework.web.client.HttpClientErrorException: 400 null
```

## Menas Stacktrace
```
org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Failed to read HTTP message: org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Invalid UTF-8 start byte 0xb0; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Invalid UTF-8 start byte 0xb0
 at [Source: (PushbackInputStream); line: 1, column: 770] (through reference chain: za.co.absa.atum.model.ControlMeasure["metadata"]->za.co.absa.atum.model.ControlMeasureMetadata["additionalInfo"])
```

## Additional context
This only happens when special characters are used on the command line, these command line arguments are saved in the `Run`'s `ControlMeasure` under `AdditionalInfo`

**Comment by GeorgiChochov** [comment]
## For release notes:
Fixed issue in `Standardization`, where a special character in the `Run` object's `Additional Info` caused the job to fail.
